Require tensorboard
This commit fixes the following error:

Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 92, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/u2/pcoppock/dlrm/venv/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'